### ISSUE TITLE
Bundle size is 6mb

### ISSUE THREAD

**Issue by Lilja-at-funnel** [makenowjust-labs/recheck#1214]
Hi!

This is my first time using recheck. When bundling, the output seems to turn out to be 6.8mb for just this package.

Does this package really need to bundle all what it's currently bundling? Is there something one can do reduce the bundle size?

**Comment by makenowjust** [comment]
Recheck contains Unicode tables for parsing and interpreting Unicode-class correctly, so the bundle size is large. Unfortunately, there is no option to drop this Unicode table from the bundle. Sorry.

**Comment by Lilja-at-funnel** [comment]
Thanks! Closing this issue then.
