### ISSUE TITLE
Regex with Java boundary matchers is shown as vulenerable

### ISSUE THREAD

**Issue by iam-nagarajan** [makenowjust-labs/recheck#1334]
# What is the problem?

Regex with Java boundary matchers is shown as vulenerable.
Example regex: `\A[^?]*\z`
Here \A and \z are boundary matchers indicating start and end of input.
But redos checker shows it as vulnerable.

<img width="770" alt="Screenshot 2024-10-24 at 9 35 54 PM" src="https://github.com/user-attachments/assets/9d03d6f5-9677-4d77-9824-746546327633">

**Comment by makenowjust** [comment]
Currently, `\A` and `\z` are not supported.

**Comment by iam-nagarajan** [comment]
@makenowjust Is it feasible to add support for it?

**Comment by makenowjust** [comment]
WIP #378.
