### ISSUE TITLE
False positive of fuzz in a busy state

### ISSUE THREAD

**Issue by falsandtru** [makenowjust-labs/recheck#447]
# What is the problem?

When the runtine environment is busy due to another concurrent build task, the recheck sometimes reports a false positive such as the `2nd degree polynomial (fuzz)`.

**Comment by makenowjust** [comment]
You should set `attackTimeout` parameter to `0` for preventing such a false positive.

**Comment by falsandtru** [comment]
Thanks, I'll try it.

**Comment by falsandtru** [comment]
I couldn't add the `attackTimeout` parameter. How can I add it?

```
[2] ERROR in .eslintrc.json:
[2]     Configuration for rule "redos/no-vulnerable" is invalid:
[2]     Value {"ignoreErrors":false,"attackTimeout":null,"timeout":20000} should NOT have additional properties.
```

**Comment by makenowjust** [comment]
Sorry. Currently `eslint-plugin-redos` does not accept all parameters (For historical reason, this plugin was maintained in another repo, and I thought it is hard to maintain parameters definition at this time.)

I'll update the plugin today or tomorrow. Thanks!

**Comment by falsandtru** [comment]
I see, I'll wait for it.

**Comment by makenowjust** [comment]
@falsandtru A new version `v4.4.0` is released. Please try it.

**Comment by falsandtru** [comment]
It works well. Thanks.
