### ISSUE TITLE
Playground report a false postive in fuzz mode

### ISSUE THREAD

**Issue by fengkx** [makenowjust-labs/recheck#682]
# What is the problem?
Playground report a false postive in fuzz mode.

Here is the input regex
```
/(?=(<table))\1(?=(\s*))\2(?<tableAttrs>(?:(?![>])[^])*)(?=(>))\4(?<tableChildren>(?=((?:(?![<])[^])*))\6)(?=(<\/table>))\7/
```

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/16515468/205220277-3bc816f0-61d3-40a8-9c77-4a4ab327f308.png">

Log: 
```
parse: start
parse: finish
  pattern: /(?=(<table))\1(?=(\s*))\2(?<tableAttrs>(?:(?![>])[^])*)(?=(>))\4(?<tableChildren>(?=((?:(?![<])[^])*))\6)(?=(<\/table>))\7/
fuzz: start (usesAcceleration: false)
fuzz: seeding start (seeder: static)
automaton: EpsNFA construction
     state size: 143
  alphabet size: 10
automaton: OrderedNFA construction
     state size: 39
  alphabet size: 10
fuzz: seeding finish
  size: 260
fuzz: iteration 1
  traces: 100
     max: '<table>\t<' (steps: 29, rate: 3.2222222222222223)
fuzz: attack start (status: limit)
  string: '/' + '<table'.repeat(168) + '<>'.repeat(159) + '<'
fuzz: attack (exponential)
fuzz: attack (polynomial: 4)
fuzz: attack succeeded (status: timeout)
  string: '/' + '<table'.repeat(269) + '<>'.repeat(260) + '<'
recall: code
const re = new RegExp('(?=(<table))\\1(?=(\\s*))\\2(?<tableAttrs>(?:(?![>])[^])*)(?=(>))\\4(?<tableChildren>(?=((?:(?![<])[^])*))\\6)(?=(<\\/table>))\\7', '');
const input = '/' + '<table'.repeat(269) + '<>'.repeat(260) + '<';
const start = Date.now();
re.exec(input);
const end = Date.now();
console.log(Number(end - start).toString());
```

Run recall code:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/16515468/205220361-9eab6fb6-800f-44fa-9f6d-72577d711053.png">
It seems cost `2ms` to run instead of `2s`

**Comment by makenowjust** [comment]
The recall phase does not work on the playground (browser) because the recall needs to spawn a process.

**Comment by fengkx** [comment]
> The recall phase does not work on the playground (browser) because it needs to spawn a process.

Try run on node.js with `RECHECK_BACKEND=native` it still report a fuzz vulnerable result. But when I ran the recall code ouput, it takes `16ms` to run. I expect it need a longer time to run?

**Comment by makenowjust** [comment]
Please set `recallTimeout` explicitly (e.g. `check('...', '', { recallTimeout: 2000 })`).

**Comment by fengkx** [comment]
Thanks, that means I need a longer recallTimeout to generate a longer attack string. This library is awesome~
