### ISSUE TITLE
eslint-plugin-redos with default config

### ISSUE THREAD

**Issue by thernstig** [makenowjust-labs/recheck#691]
# What is the problem?

When configuring ESLint, one currently has to do this:

```json
"plugins": ["redos"],
"rules": {
   "redos/no-vulnerable": "error"
 }
```

I t would be nice to use a very common config functionality of ESLint where both the plugin and the rule is loaded only once.

# How to fix the problem?

Add an ESLint config to esling-plugin-redos and let us specify it like:

```json
  "extends": [
    "plugin:redos/recommended"
  ],
```

Read more at https://eslint.org/docs/latest/developer-guide/working-with-plugins#configs-in-plugins (overview at https://stackoverflow.com/a/54522973/1853417)

**Comment by makenowjust** [comment]
Sounds good.

When I created the ESLint plugin, Recheck was unstable, and I was uncomfortable enforcing errors as the default setting. However, Recheck is now stable enough to be used on a daily basis. 

It is a simple fix, so please send us a pull request, and I will merge it.

**Comment by makenowjust** [comment]
@thernstig I added the `recommended` config, and v4.4.2 have been published. You can use `"extends": ["plugin:redos/recommended"]` now. Thanks.
