### ISSUE TITLE
Fails on Node 14 since bump to 4.4.2

### ISSUE THREAD

**Issue by kristian** [makenowjust-labs/recheck#728]
# What is the problem?

Since the revision bump from 4.4.1 to 4.4.2 the library fails on Node 14, due to a:

```SyntaxError: Unexpected token '||='```

The ```||=``` logical or statement was only introduced in Node 15, see [1]. After downgrading to 4.4.1, the library started to work fine again.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility

# How to fix the problem?

Downgrade to 4.4.1.

**Comment by makenowjust** [comment]
It is already fixed in HEAD (See #708). Please wait for a new release.

**Comment by kristian** [comment]
Thanks for the quick response!
