### ISSUE TITLE
Is there any guidance document?Thanks!

### ISSUE THREAD

**Issue by heyyuyu** [makenowjust-labs/recheck#741]

**Comment by makenowjust** [comment]
Sorry. For now, there is no "Getting Started" document. How to introduce ESLint plugin is described [here](https://makenowjust-labs.github.io/recheck/docs/usage/as-eslint-plugin/).

@heyyuyu What contents do you want in a guidance (Getting Started) document?

**Comment by heyyuyu** [comment]
"Getting Started" document,That's what I want,Thanks

> Sorry. For now, there is no "Getting Started" document. How to introduce ESLint plugin is described [here](https://makenowjust-labs.github.io/recheck/docs/usage/as-eslint-plugin/).
> 
> @heyyuyu What contents do you want in a guidance (Getting Started) document?

"Getting Started" document,That's what I want,Thanks
