### ISSUE TITLE
Document how to build from scratch

### ISSUE THREAD

**Issue by bastien-roucaries** [makenowjust-labs/recheck#791]
Hi,

I wish to package recheck for debian.

Could you document how to rebuild from stratch ?

Bastien (rouca)

**Comment by makenowjust** [comment]
In my experience, the "How to build" document is the most difficult to maintain. I don't have enough time to maintain such documents, and outdated documents can confuse users. Therefore, I am against adding such a document.

But I can answer questions about "How to build" here. First, please tell me what you want to build. This repository contains three kinds of artifacts: the Scala library, the NPM package, and the native binary (`recheck` CLI). The build methods are different depending on which one you want to build.

**Comment by bastien-roucaries** [comment]
Hi,

I want to build the recheck cli including the dependencies if needed (the scala library I think) and the npm package

**Comment by makenowjust** [comment]
Please try the following instructions:

1. Install JVM and `sbt` (I am not sure which version of JDK is needed, but I think JDK 8 or 9 is invalid, and 11 or higher is recommended.)
2. Clone this repository.
3. Run `sbt cli/assembly cli/nativeImage` under the directory of the cloned repository. This command builds Scala.js artifact, `recheck.jar` and `recheck` native binary.

This yields the following file.

- `modules/recheck-cli/target/scala-2.13/recheck.jar` (executable jar)
- `modules/recheck-cli/target/native-image/recheck` (native binary)

For packaging the CLI, the above instructions are sufficient. The NPM package build method is hard to explain, so we will explain it if necessary (But, I don't know much about packaging to Debian, so I don't know if I can help you).

Finally, [GitHub actions workflow](https://github.com/makenowjust-labs/recheck/blob/98601883fee1b8945fb3397ef142bdea7d704ac8/.github/workflows/main.yml) may help you. Thank you.

**Comment by makenowjust** [comment]
@bastien-roucaries Is there any progress?

**Comment by makenowjust** [comment]
Close because there are no responses.
