### ISSUE TITLE
eslint-plugin-redos cache config is not working

### ISSUE THREAD

**Issue by mdenkinger** [makenowjust-labs/recheck#943]
# What is the problem?

Activating the cache in `eslint-plugin-redos` like [documented](https://makenowjust-labs.github.io/recheck/docs/usage/as-eslint-plugin/) in the recheck docs causes an eslint validation error.

```
Configuration for rule "redos/no-vulnerable" is invalid:
        Value {"cache":true} should NOT have additional properties. 
```

`.eslintrc`
```
  plugins: ['redos'],
  rules: {
    'redos/no-vulnerable': ['error', { cache: true }],
  }
```

Example on [stackblitz.com](https://stackblitz.com/edit/node-qzgyz1?file=.eslintrc.js)

# How to fix the problem?

(?)

# Related issues

-

**Comment by makenowjust** [comment]
Your `eslint-plugin-redos` seems to be old. `cache` option was added from `4.5.0-beta.1`, and the latest version is `4.5.0-beta.4`, but your example uses `4.4.5`. Could you check the version?

**Comment by mdenkinger** [comment]
Using a 4.5.0-beta.1+ version solved the issue. Thanks for the fast reply.
