### ISSUE TITLE
Regex DoS check timesout

### ISSUE THREAD

**Issue by ajinabraham** [makenowjust-labs/recheck#992]
# What is the problem?

https://devina.io/redos-checker

Regex: `\.loadUrl\(.{0,48}getExternalStorageDirectory\(` works fine - > `Safe to use`
Regex: `\.loadUrl\(.{0,49}getExternalStorageDirectory\(` times out. - > `Oh no! The checker timed out`

# How to fix the problem?

# Related issues

**Comment by makenowjust** [comment]
You can use the official playground instead: <https://makenowjust-labs.github.io/recheck/playground/>.
This can change parameters. You can use `automaton` checker in this case. It can check correctly.
